import { RHPlatformAccount } from '../types';

export const DEFAULT_RH_PLATFORMS: RHPlatformAccount[] = [
  {
    id: 'catho',
    name: 'Catho',
    domain: 'catho.com.br',
    badgeColor: '#E65100',
    accentBg: 'rgba(230, 81, 0, 0.12)',
    loginUrl: 'https://www.catho.com.br/login',
    searchJobUrlTemplate: 'https://www.catho.com.br/vagas/{keyword}/{city}-{state}/',
    searchCandidateUrlTemplate: 'https://www.catho.com.br/curriculos/buscar?q={keyword}&cidade={city}&uf={state}',
    usernameOrEmail: '',
    password: '',
    accountType: 'Assinante VIP / Premium',
    hasCredentials: false,
    enabledForSearch: true,
    authNotes: 'Permite visualização de currículos completos de assinantes e candidatura rápida a vagas restritas.',
  },
  {
    id: 'empregos',
    name: 'Empregos.com.br',
    domain: 'empregos.com.br',
    badgeColor: '#059669',
    accentBg: 'rgba(5, 150, 105, 0.12)',
    loginUrl: 'https://www.empregos.com.br/login',
    searchJobUrlTemplate: 'https://www.empregos.com.br/vagas/{keyword}/{city}-{state}',
    searchCandidateUrlTemplate: 'https://www.empregos.com.br/curriculos/{keyword}/{city}-{state}',
    usernameOrEmail: '',
    password: '',
    accountType: 'Assinante VIP / Premium',
    hasCredentials: false,
    enabledForSearch: true,
    authNotes: 'Acesso prioritário a banco de dados de talentos e vagas diretas de RH empresarial.',
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    domain: 'linkedin.com',
    badgeColor: '#0A66C2',
    accentBg: 'rgba(10, 102, 194, 0.12)',
    loginUrl: 'https://www.linkedin.com/login',
    searchJobUrlTemplate: 'https://www.linkedin.com/jobs/search/?keywords={keyword}&location={city}%2C%20{state}',
    searchCandidateUrlTemplate: 'https://www.linkedin.com/search/results/people/?keywords={keyword}&geoUrn=Brazil',
    usernameOrEmail: '',
    password: '',
    accountType: 'Recrutador / Empresa',
    hasCredentials: false,
    enabledForSearch: true,
    authNotes: 'Sourcing corporativo de alto nível, mensagens diretas InMail e candidaturas simplificadas Easy Apply.',
  },
  {
    id: 'infojobs',
    name: 'InfoJobs',
    domain: 'infojobs.com.br',
    badgeColor: '#7C3AED',
    accentBg: 'rgba(124, 58, 237, 0.12)',
    loginUrl: 'https://www.infojobs.com.br/candidate/login.aspx',
    searchJobUrlTemplate: 'https://www.infojobs.com.br/vagas-de-emprego-{keyword}-em-{city}.aspx',
    searchCandidateUrlTemplate: 'https://www.infojobs.com.br/candidate/search',
    usernameOrEmail: '',
    password: '',
    accountType: 'Candidato',
    hasCredentials: false,
    enabledForSearch: true,
    authNotes: 'Ampla base nacional com testes de compatibilidade e comunicação direta com recrutadores.',
  },
  {
    id: 'gupy',
    name: 'Gupy',
    domain: 'gupy.io',
    badgeColor: '#DB2777',
    accentBg: 'rgba(219, 39, 119, 0.12)',
    loginUrl: 'https://login.gupy.io/',
    searchJobUrlTemplate: 'https://portal.gupy.io/job-search/term={keyword}',
    searchCandidateUrlTemplate: 'https://empresa.gupy.io/',
    usernameOrEmail: '',
    password: '',
    accountType: 'Candidato',
    hasCredentials: false,
    enabledForSearch: true,
    authNotes: 'Ecossistema ATS de ponta das maiores empresas do Brasil com inteligência Gaia.',
  },
  {
    id: 'vagas',
    name: 'Vagas.com',
    domain: 'vagas.com.br',
    badgeColor: '#DC2626',
    accentBg: 'rgba(220, 38, 38, 0.12)',
    loginUrl: 'https://www.vagas.com.br/login-candidato',
    searchJobUrlTemplate: 'https://www.vagas.com.br/vagas-de-{keyword}-em-{city}',
    searchCandidateUrlTemplate: 'https://www.vagas.com.br/',
    usernameOrEmail: '',
    password: '',
    accountType: 'Candidato',
    hasCredentials: false,
    enabledForSearch: true,
    authNotes: 'Portal tradicional com vagas exclusivas para multinacionais e grandes grupos corporativos.',
  },
];
